# Exported from:        http://erina:5516/
# Release version:      26.3.0-713.1100

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: level1/level2
  home: FolderF/level1/level2
spec:
- notifications: []
  inheritFromParent: true
