# Exported from:        http://erina:5516/
# Release version:      25.3.5-SNAPSHOT
# Date created:         Wed May 06 12:27:13 IST 2026

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: folder A/folder B
  home: root%2Ffolder A/folder A/folder B
spec:
- template: templateB_crt
  scheduledStartDate: 2026-05-06T09:00:00+05:30
  phases:
  - phase: phase B1
    tasks:
    - name: "1_9"
      type: xlrelease.CreateReleaseTask
      newReleaseTitle: crt_1_9
      template: root/folder A/folder B/Template B
      folder: root/folder A/folder B
    color: "#3d6c9e"
  scriptUsername: admin
  scriptUserPassword: !value "xlrelease_Release_templateB_crt_scriptUserPassword"
  riskProfile: Default risk profile
  author: admin
