# Exported from:        http://erina:5516/
# Release version:      26.1.2-SNAPSHOT

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: Folder B
  home: Folder A/Folder B
spec:
- template: Template B
  scheduledStartDate: 2026-05-09T09:00:00+05:30
  phases:
  - phase: phase B
    color: "#3d6c9e"
  scriptUsername: admin
  scriptUserPassword: !value "xlrelease_Release_Template_B_scriptUserPassword"
  riskProfile: Default risk profile
  author: admin
