# Exported from:        http://erina:5516/
# Release version:      26.1.2-SNAPSHOT

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: Folder B
  home: Folder A/Folder B
spec:
- template: templateB_crt
  scheduledStartDate: 2026-05-19T09:00:00+05:30
  phases:
  - phase: phase B2
    tasks:
    - name: "1.9"
      type: xlrelease.CreateReleaseTask
      newReleaseTitle: crt_1_9
      template: ./TemplateB
      folder: ./
    color: "#3d6c9e"
  riskProfile: Default risk profile
  author: admin
