# Exported from:        http://erina:5516/
# Release version:      25.3.5-SNAPSHOT
# Date created:         Thu May 07 16:35:16 IST 2026

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: test C
  home: test A%2Ftest B%2Ftest C/test C
spec:
- template: template c
  scheduledStartDate: 2026-05-07T09:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: crt_test
      type: xlrelease.CreateReleaseTask
      newReleaseTitle: crt
      template: test A/test B/template B
      folder: test A/test B
    - name: crttt
      type: xlrelease.CreateReleaseTask
      newReleaseTitle: crt_demo
      template: Erina A/Template Erina A
      folder: Erina A
  riskProfile: Default risk profile
  author: admin
