# Exported from:        http://erina:5516/
# Release version:      26.1.2-SNAPSHOT

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: Folder A/Folder B/Folder C
spec:
- template: Template C
  scheduledStartDate: 2026-05-09T09:00:00+05:30
  phases:
  - phase: phase C
    tasks:
    - name: "1.2"
      type: xlrelease.CreateReleaseTask
      newReleaseTitle: crt_1_2
      template: Folder A/Folder B/Template B
      folder: Folder A/Folder B
    - name: "1.3"
      type: xlrelease.CreateReleaseTask
      newReleaseTitle: crt_1_3
      template: Folder A/Folder B2/Template B2
      folder: Folder A/Folder B2
    - name: "1.4"
      type: xlrelease.CreateReleaseTask
      newReleaseTitle: crt_1_4
      template: Folder A2/Template A2
      folder: Folder A2
    - name: "1.5"
      type: xlrelease.CreateReleaseTask
      newReleaseTitle: crt_1_5
      template: Folder A/Folder B/Template B
      folder: Folder A/Folder B
    color: "#3d6c9e"
  scriptUsername: admin
  scriptUserPassword: !value "xlrelease_Release_Template_C_scriptUserPassword"
  riskProfile: Default risk profile
  author: admin
