# Exported from:        http://erina:5516/
# Release version:      25.3.5-SNAPSHOT
# Date created:         Thu May 07 13:09:07 IST 2026

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: Erina B
  home: Erina A/Erina B
spec:
- template: Template Erina B
  scheduledStartDate: 2026-05-06T09:00:00+05:30
  dueDate: 2026-05-06T10:00:00+05:30
  phases:
  - phase: erina2
    color: "#3d6c9e"
  scriptUsername: admin
  scriptUserPassword: !value "xlrelease_Release_Template_Erina_B_scriptUserPassword"
  riskProfile: Default risk profile
  author: admin
