# Exported from:        http://erina:5516/
# Release version:      26.1.0-SNAPSHOT

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: D-43333 testt
spec:
- template: CRT-Version-Test
  scheduledStartDate: 2026-07-22T09:00:00+05:30
  dueDate: 2026-07-22T10:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: crt1
      type: xlrelease.CreateReleaseTask
      newReleaseTitle: release1
      template: "${folder.parent-template}"
      folder: "${folder.target-folder}"
    - name: crt2
      type: xlrelease.CreateReleaseTask
      newReleaseTitle: release2
      template: "${folder.parent-template}"
      folder: ./
    - name: crt3
      type: xlrelease.CreateReleaseTask
      newReleaseTitle: release3
      template: "${folder.parent-template}"
      folder: "${folder.target-folder}"
    - name: crt4
      type: xlrelease.CreateReleaseTask
      newReleaseTitle: release4
      template: ./dummy
      folder: ./
  riskProfile: Default risk profile
  author: admin
