# Exported from:        http://erina:5516/
# Release version:      26.3.0-713.1100

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: level1/level2/level3/level4a/level5
  home: FolderF/level1/level2/level3/level4a/level5
spec:
- template: template5
  scheduledStartDate: 2026-07-17T09:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: crt5
      type: xlrelease.CreateReleaseTask
      newReleaseTitle: r5
      template: ../../../../../templateF
      folder: ../../../../..
  riskProfile: Default risk profile
  author: admin
