# Exported from:        http://erina:5516/
# Release version:      26.1.2-SNAPSHOT

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: Folder B2
  home: Folder A/Folder B2
spec:
- template: Template B2
  scheduledStartDate: 2026-05-09T09:00:00+05:30
  dueDate: 2026-05-09T10:00:00+05:30
  phases:
  - phase: phase B2
    color: "#3d6c9e"
  scriptUsername: admin
  scriptUserPassword: !value "xlrelease_Release_Template_B2_scriptUserPassword"
  riskProfile: Default risk profile
  author: admin
