# Exported from:        http://erina:5516/
# Release version:      26.3.0-SNAPSHOT

---
apiVersion: xl-release/v1
kind: Permissions
metadata:
  path: FolderC
  home: FolderA/FolderB/FolderC
spec:
- directory: "."
  inheritFromParent: true
