# Exported from:        http://erina:5516/
# Release version:      26.3.0-SNAPSHOT

---
apiVersion: xl-release/v1
kind: Permissions
metadata:
  path: FolderB2/FolderC3
  home: FolderA/FolderB2/FolderC3
spec:
- directory: "."
  inheritFromParent: true
