# Exported from:        http://erina:5516/
# Release version:      25.3.5-SNAPSHOT
# Date created:         Wed May 06 10:08:48 IST 2026

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: folder A
  home: root%2Ffolder A/folder A
spec:
- name: test1.1
  type: git.Repository
  url: https://github.com/ErinaDAI/test_repo
  username: ErinaDAI
  password: !value "git_Repository_test1_1_password"
  gitProvider: GITHUB
