# Exported from:        http://erina:5516/
# Release version:      26.3.0-SNAPSHOT

---
apiVersion: xl-release/v1
kind: Permissions
metadata:
  path: /
  home: FolderA
spec:
- directory: "."
  teams:
  - name: Template Owner
    users:
    - admin
    permissions:
    - template#view
    - template#edit
    - template#create_release
    - folder#view
  - name: Release Admin
    users:
    - admin
    permissions:
    - release#start
    - release#view
    - release#edit
  - name: Folder Owner
    users:
    - admin
    - adm
    permissions:
    - folder#apply_changes
    - folder#view
    - folder#edit
