# Exported from:        http://erina:5516/
# Release version:      26.3.0-SNAPSHOT

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Notifications.yaml
  - Template_api_validation_template.yaml
  - Template_t1.yaml
  - Template_templatea.yaml
  - Trigger_trigger_re_e_5e1.yaml
