# Exported from:        http://erina:5516/
# Release version:      26.3.0-SNAPSHOT

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: FolderB2/FolderC4
  home: FolderA/FolderB2/FolderC4
spec:
- name: ChildC4
  type: git.Repository
  url: https://github.com/ErinaDAI/test_repo
  username: ErinaDAI
  password: !value "git_Repository_ChildC4_password"
  gitProvider: GITHUB
