# Exported from:        http://erina:5516/
# Release version:      26.3.0-SNAPSHOT

---
apiVersion: xl-release/v1
kind: Permissions
metadata:
  path: FolderB2/FolderC4
  home: FolderA/FolderB2/FolderC4
spec:
- directory: "."
  teams:
  - name: qa team
    users:
    - test1
    - admin
    permissions:
    - template#view
    - folder#edit_teams
    - template#edit_precondition
    - folder#view
    - folder#edit_variables
    - release#view
    - template#edit_failure_handler
    - folder#edit
    - folder#edit_security
    - folder#edit_notifications
    - template#edit
    - folder#view_security
  - name: Template Owner
    users:
    - admin
    permissions:
    - template#create_release
    - folder#view
    - template#view
    - template#edit
  - name: Release Admin
    users:
    - admin
    permissions:
    - release#view
    - release#edit
    - release#start
  - name: Folder Owner
    users:
    - adm
    - admin
    permissions:
    - folder#apply_changes
    - folder#edit
    - folder#view
