# Exported from:        http://erina:5516/
# Release version:      26.3.0-901.847

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: C2
  home: A/B1/C2
spec:
- notifications: []
  inheritFromParent: true
