# Exported from:        http://erina:5516/
# Release version:      25.3.5-SNAPSHOT
# Date created:         Thu May 14 15:11:05 IST 2026

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: Folder B/Folder C
  home: Folder A/Folder B/Folder C
spec:
- name: demo_C
  type: git.Repository
  url: https://github.com/ErinaDAI/test_repo
  username: ErinaDAI
  password: !value "git_Repository_demo_C_password"
  gitProvider: GITHUB
