# Exported from:        http://erina:5516/
# Release version:      26.1.2-SNAPSHOT

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: Folder B/Folder C
  home: Folder A/Folder B/Folder C
spec:
- template: TemplateC2
  scheduledStartDate: 2026-05-21T09:00:00+05:30
  phases:
  - phase: phaseC2
    color: "#3d6c9e"
  riskProfile: Default risk profile
  author: admin
