# Exported from:        http://erina:5516/
# Release version:      26.3.0-SNAPSHOT

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Dashboard_folderrrr_dash.yaml
  - Notifications.yaml
  - Template_cant_find_me_ahahah.yaml
  - Template_testt.yaml
  - Trigger_triggerrererererer.yaml
