# Exported from:        http://erina:5516/
# Release version:      26.3.0-SNAPSHOT

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: Folder/Folderrrrr
spec:
- name: triggerrererererer
  type: time.Schedule
  releaseTitle: re!eA5e by tr!ggerr >_< eehee
  template: testt
  periodicity: 0 * * * * *
  triggerTime: 2026-07-15T12:01:00.083000
