# Exported from:        http://erina:5516/
# Release version:      25.3.9-726.1600
# Date created:         Tue Aug 04 11:21:51 IST 2026

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Notifications.yaml
  - Template_crt-version-test.yaml
  - Template_parent-template.yaml
  - Variables.yaml
