# Exported from:        http://erina:5516/
# Release version:      26.3.0-SNAPSHOT

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: testt
spec:
- template: CRT-Version-Test
  scheduledStartDate: 2026-07-15T09:00:00+05:30
  phases:
  - phase: New Phase
    tasks:
    - name: CRT1
      type: xlrelease.CreateReleaseTask
      newReleaseTitle: release1
      template: "${folder.parent-template}"
      folder: ./
    - name: CRT2
      type: xlrelease.CreateReleaseTask
      newReleaseTitle: release2
      template: "${folder.parent-template}"
      folder: ./
  riskProfile: Default risk profile
  author: admin
